### ISSUE TITLE
Ys 2 FM version

### ISSUE THREAD

**Issue by bladeba** [mmlbox/ys2413#1]
Hi!!!

I'm Victor Martinez.

I'm creating a FM+PSG version of Ys2 for MSX. It would be great if I could use your songs....

Please.. contact me!!!

My email:   bladeba1977@gmail.com

**Comment by mmlbox** [comment]
Hi 

i am very sorry for i lately noticed this post. I saw your awesome patched version of YS2 on YouTube.  Thank you very much.

**Comment by bladeba** [comment]
Wooowww! Thanks to you!

You did a great job with those songs!

**Comment by mmlbox** [comment]
As for FM+PSG version, all songs have been added. https://youtu.be/BEif7FnbdfQ

**Comment by bladeba** [comment]
Simply amazing job....

I'll include them in my HHD version...

Thanks!!
